all:
	gcc -Wall -o eorder_gen order_gen.c -lpthread -lrt
	gcc -Wall -o eplanificadorBrazosRoboticos planificadorBrazosRoboticos.c -lpthread -lrt
clean:
	rm eorder_gens
	rm eplanificadorBrazosRoboticos