all:
	gcc -Wall -o eorder_gen order_gen.c -lpthread -lrt
	gcc -Wall -o eplanificadorBrazosR planificadorBrazosR.c -lpthread -lrt
	gcc -Wall -o eadmin admin.c -lpthread -lrt
clean:
	rm eorder_gen
	rm eplanificadorBrazosR
	rm eadmin